# Generated by Django 3.0.7 on 2020-06-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
