# Generated by Django 3.0.7 on 2020-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veva_pcs', '0005_auto_20200709_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=100),
        ),
    ]
