# Generated by Django 3.0.7 on 2020-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veva_pcs', '0006_auto_20200709_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=599.99, max_digits=10000),
        ),
    ]
