# Generated by Django 3.0.6 on 2020-09-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veva_pcs', '0007_auto_20200710_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_image'),
        ),
    ]
